CREATE TRIGGER trg_KiemTraBan
ON BANHOADON
FOR INSERT, UPDATE AS
BEGIN
	DECLARE @MaHD char(16), @MaKhu char(3), @STT int, @MaHD_DangNgoi char(16), @GioVao time(7), @Ngay date
	SELECT	@MaHD=MAHOADON FROM inserted
	SELECT	@MaKhu=MAKHU, @STT=SOTHUTU
	FROM	inserted
	WHERE	MAHOADON=@MaHD

	SELECT	@GioVao=GIOVAO, @Ngay=NGAY
	FROM	HOADON
	WHERE	MAHOADON=@MaHD

	SELECT	@MaHD_DangNgoi=B.MAHOADON
	FROM	BANHOADON B, HOADON HD
	WHERE	B.MAHOADON=HD.MAHOADON AND HD.NGAY=@Ngay AND HD.GIOVAO<@GioVao AND (HD.GIORA IS NULL OR HD.GIORA>@GioVao) AND B.MAKHU=@MaKhu AND B.SOTHUTU=@STT

	IF @MaHD_DangNgoi IS NOT NULL
	BEGIN
		RAISERROR('CO NGUOI DANG NGOI BAN NAY !!!', 16, 1)
		ROLLBACK
	END
END